import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  throw new Error("erro layout root");
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-5 text-center bg-red-500 text-white">
          Layout da home
        </div>
        {children}
      </body>
    </html>
  );
}
